### ISSUE TITLE
Odin Land cần sửa

### ISSUE THREAD

**Issue by tanlucbui** [caresvn/odinland.vn#47]
- [x] Phần comment bên dưới mỗi bài viết, anh cho Form điền thông tin của mình. Cái này em thấy nó là mặt định của trang luôn hay sao ấy.
- [x] Anh cho thêm link vào phần ảnh đại diện của mỗi bài viết tin tức.
- [x] Trong trang tin tức thêm 2 mục: Tư vấn Bồ Đào Nha, Tư vấn Síp.
- [x] Thumnail ngoài trang chủ bị cái bé, cái to.
- [x] Trang tin tức bên tiếng anh bị lỗi.
- [x] Contact form bị lỗi không gửi được, dịch form sang tiếng anh em không biết chỗ dịch.

**Comment by tanlucbui** [comment]
![loi odin land 3](https://user-images.githubusercontent.com/44955460/48321487-75eee800-e655-11e8-9982-0b138e25b90f.PNG)
![loi odin land 4](https://user-images.githubusercontent.com/44955460/48321488-76877e80-e655-11e8-8a1e-d05f963dfa20.PNG)
![loi odin land 5](https://user-images.githubusercontent.com/44955460/48321489-76877e80-e655-11e8-8a02-2ce514f0c18d.PNG)
![loi odin land 6](https://user-images.githubusercontent.com/44955460/48321490-76877e80-e655-11e8-9c60-f199a56465c8.PNG)
![loi odinland 2](https://user-images.githubusercontent.com/44955460/48321491-77201500-e655-11e8-96fc-074d9429ebef.PNG)
![loi odinland l](https://user-images.githubusercontent.com/44955460/48321492-77201500-e655-11e8-9ebf-f93d0c99ab07.PNG)

**Comment by khoipro** [comment]
~Trang tin tức bên tiếng anh bị lỗi.~

**Comment by khoipro** [comment]
~Trong trang tin tức thêm 2 mục: Tư vấn Bồ Đào Nha, Tư vấn Síp.~

**Comment by khoipro** [comment]
~Translate Contact Form in English and test sending~

<img width="511" alt="screenshot at nov 12 21-46-01" src="https://user-images.githubusercontent.com/10395311/48354467-65c22180-e6c4-11e8-9082-9a095c366251.png">

Hướng dẫn cách tạo form:

<img width="613" alt="screenshot at nov 12 21-46-57" src="https://user-images.githubusercontent.com/10395311/48354610-b6d21580-e6c4-11e8-833d-a07ea1341245.png">

**Comment by khoipro** [comment]
Hướng dẫn sử dụng shortcode trong trang:

<img width="462" alt="screenshot at nov 12 21-50-41" src="https://user-images.githubusercontent.com/10395311/48354745-044e8280-e6c5-11e8-8f62-f1c288cece53.png">

Tài liệu đã cập nhật: https://github.com/caresvn/odinland.vn/wiki/Configure-Contact-Form-7

**Comment by khoipro** [comment]
Đã cho nhập shortcode trong Theme Options > Single Post. Shortcode này có trong này: http://odlvn.test/wp-admin/admin.php?page=wpcf7 sau khi tạo form ra.

<img width="374" alt="screenshot at nov 12 22-29-12" src="https://user-images.githubusercontent.com/10395311/48357134-6fe71e80-e6ca-11e8-901c-31a5dcb1c169.png">

**Comment by khoipro** [comment]
Hiển thị của form sau khi nhập shortcode:

<img width="463" alt="screenshot at nov 12 22-30-29" src="https://user-images.githubusercontent.com/10395311/48357198-96a55500-e6ca-11e8-86b0-a7759d7be951.png">

**Comment by khoipro** [comment]
~Link vào phần ảnh đại diện của mỗi bài viết tin tức~

**Comment by khoipro** [comment]
Đã fix tất cả lỗi được report.
