### ISSUE TITLE
Anh xem giúp em cái http:// và https://

### ISSUE THREAD

**Issue by tanlucbui** [caresvn/odinland.vn#50]
Hiện tại, em định sử dụng cái bắt số điện thoại khi khách hàng vào website.
Tuy nhiên, http:// thì mới bắt được, còn https:// thì không bắt được.
Anh xem có nên ngắt nó một thời gian để chạy quảng cáo cho nó không

**Comment by khoipro** [comment]
@tanlucbui cái này không bỏ ra được vì sẽ bị cảnh báo không an toàn trên trình duyệt Chrome em nhé.
