### ISSUE TITLE
Vấn đề cần chỉnh sửa.

### ISSUE THREAD

**Issue by tanlucbui** [caresvn/odinland.vn#51]
1. Khi ấn vào Văn phòng Dịch vụ ở Đà Nẵng thì vẫn ra Văn Phòng cho thuê.
2. Sửa phần liên hệ trong mỗi bài viết. Anh xem ảnh đính kèm.
![1](https://user-images.githubusercontent.com/44955460/48875579-58c3d180-ee2c-11e8-9578-f6a354eb8918.jpg)
![2](https://user-images.githubusercontent.com/44955460/48875581-59f4fe80-ee2c-11e8-82e0-6181e5ad843d.jpg)

**Comment by khoipro** [comment]
Đã fix.
