### ISSUE TITLE
Anh sửa lại cái slide ảnh trong mỗi bài viết dự án giúp em.

### ISSUE THREAD

**Issue by tanlucbui** [caresvn/odinland.vn#52]
Em không biết anh làm việc như thế nào với anh Minh. Nhưng a Minh vừa bảo em nói anh sửa lại cái slide, em nghĩ anh cho slide trở lại như cũ bình thường. Chữ nằm trong ảnh, và có một lớp nền đen mờ cho silde để cho nó nổi bật.
![1](https://user-images.githubusercontent.com/44955460/48883043-64c18a80-ee50-11e8-8e29-f3f660edc664.jpg)

**Comment by khoipro** [comment]
Đã fix.
