### ISSUE TITLE
Pop Up và tạo trang bán hàng mới

### ISSUE THREAD

**Issue by tanlucbui** [caresvn/odinland.vn#53]
Anh Khôi, A Minh bảo em hỏi anh khi nào mình có Popup website. Bên em định chạy quảng cáo định cư trên website .vn

1. Anh xem làm Popup cho bên em.

2. Anh xem tạo thêm 1 thang con để giới thiệu về chương trình hội thảo. Cái này chắc phải cần anh tư vấn thêm.

**Comment by khoipro** [comment]
~Popup xong lâu rồi nhé~

**Comment by khoipro** [comment]
~Chương trình hội thào cũng xong rồi.~
