### ISSUE TITLE
Nội dung và hình ảnh Popup

### ISSUE THREAD

**Issue by tanlucbui** [caresvn/odinland.vn#54]
Anh check file đính kèm
![banner-chau-au](https://user-images.githubusercontent.com/44955460/48997571-fe57a780-f182-11e8-86c8-681b5601ebc6.jpg)
[noi dung popup.docx](https://github.com/caresvn/odinland.vn/files/2614379/noi.dung.popup.docx)

**Comment by tanlucbui** [comment]
Anh kèm theo form đăng kí nữa nhé

**Comment by khoipro** [comment]
Thêm popup mới:

![add-new-popup](https://user-images.githubusercontent.com/10395311/49055166-40d3bf80-f229-11e8-811e-9a8ba2a1207c.png)

Sửa nội dung trong popup:

![edit-popup-content](https://user-images.githubusercontent.com/10395311/49055267-82fd0100-f229-11e8-9454-677e89e8f1f5.png)

Có thể thêm shortcode như của contact form.

Chỉnh điều kiện hiển thị trong các trang nào:

![edit-popup-location](https://user-images.githubusercontent.com/10395311/49055284-a1fb9300-f229-11e8-9eef-f870d870d9ca.png)

![edit-popup-display](https://user-images.githubusercontent.com/10395311/49055376-ebe47900-f229-11e8-997d-e8864d2e2669.png)

Chỉnh **Position** (vị trí trên màn hình) và **Trigger** (hành động nào sẽ mở popup)
