### ISSUE TITLE
Popup odinland.vn

### ISSUE THREAD

**Issue by tanlucbui** [caresvn/odinland.vn#55]
Anh xem chỉnh lại Popup cho nó xuất hiện ngoài trang chủ, A 
Minh muốn nó nằm ngoài trang chủ.

**Comment by khoipro** [comment]
Em sửa điều kiện [ở đây](https://odinland.vn/wp-admin/post.php?post=2361&action=edit) được nhé: 

![screenshot at nov 27 09-38-05](https://user-images.githubusercontent.com/10395311/49054838-2d742480-f228-11e8-8b1c-927174372aab.png)

**Comment by khoipro** [comment]
@tanlucbui set "Page Template" sang thành Homepage là ok.
