### ISSUE TITLE
Cần sửa lại trang sự kiện

### ISSUE THREAD

**Issue by tanlucbui** [caresvn/odinland.vn#56]
Dear Anh !

Em có note trong hình, anh sửa y chang vậy là xong rồi.
![form dang ki](https://user-images.githubusercontent.com/44955460/49266597-665f0400-f489-11e8-9bfb-1e93f1177e5b.PNG)

**Comment by khoipro** [comment]
Đã fix phần contact form.
Phần button @tanlucbui  tự đổi rồi nhé.
