### ISSUE TITLE
Sửa Form

### ISSUE THREAD

**Issue by tanlucbui** [caresvn/odinland.vn#57]
A Khôi làm form nhỏ thôi... form hiện tại To quá.

**Comment by tanlucbui** [comment]
Form sự kiện

**Comment by khoipro** [comment]
Đã điều chỉnh lại kích thước form.

<img width="582" alt="screenshot at dec 02 23-06-57" src="https://user-images.githubusercontent.com/10395311/49341962-0170fd00-f687-11e8-92e2-aaf642cec087.png">
