### ISSUE TITLE
Form popup bị lỗi

### ISSUE THREAD

**Issue by tanlucbui** [caresvn/odinland.vn#58]
Anh xem giúp em cái form Pop Up bên .vn khi a Minh vào odinland.vn nó bị dính một chỗ kéo lên kéo xuống mà nó vẫn đứng 1 chỗ. Nó không trượt theo

Em vào thì nó vẫn bị y chang  A Minh.

**Comment by khoipro** [comment]
Lỗi này không gặp nữa, lưu ý do content quá dài thì mới bị.
