### ISSUE TITLE
Lỗi .vn bên tiếng anh

### ISSUE THREAD

**Issue by tanlucbui** [caresvn/odinland.vn#59]
Anh xem ngoài trang chủ mục dự án của bên tiếng anh. Ảnh đại diện nó bị to

https://odinland.vn/?lang=en

**Comment by khoipro** [comment]
Thiếu ảnh screenshot chỉ ra phần nào ảnh to. Cần lưu ý khi cắt ảnh thì trọng tâm của ảnh phải nằm chính giữa nhé @tanlucbui

**Comment by khoipro** [comment]
Anh không thấy ảnh screenshot nên không rõ ảnh nào bị.
