### ISSUE TITLE
Thêm tính năng mới cho website .vn

### ISSUE THREAD

**Issue by tanlucbui** [caresvn/odinland.vn#61]
Dear Anh !
Mr Minh vừa bảo em:

Slide ngoài trang chủ chuyển sang hết slide của các bài định cư bồ đào nha và síp. Không để slide dự án nữa, em vào trang chủ thì chưa có mục để thêm slide của phần định cư vào.

Em không cấu hình được phần này, anh xem giúp em nhé

**Comment by khoipro** [comment]
Tính năng này đã có, chọn "Static Content" là cấu hình được cho dữ liệu không phải là dự án.
