### ISSUE TITLE
Lỗi phần news bên tiếng anh

### ISSUE THREAD

**Issue by tanlucbui** [caresvn/odinland.vn#62]
Anh xem hình giúp em nhé
![nothing found](https://user-images.githubusercontent.com/44955460/50258066-9c602a00-0430-11e9-9d86-c83c3d4fcf85.PNG)

**Comment by khoipro** [comment]
Phần này do em đã bỏ link `/category/` dẫn tới bị sai nhé. Anh đã sửa lại rồi @tanlucbui b


Đường dẫn đúng phải là https://odinland.vn/category/news/?lang=en

![screenshot at dec 20 20-31-30](https://user-images.githubusercontent.com/10395311/50287746-55a51b00-0496-11e9-94b3-7eef345ae6d3.png)
