### ISSUE TITLE
Mình không bỏ được chữ category hả anh

### ISSUE THREAD

**Issue by tanlucbui** [caresvn/odinland.vn#63]
Bây giờ cả tiếng việt và tiếng anh điều không hiển thị phần tin tức luôn rồi anh, em chưa đụng gì vào cả.

**Comment by khoipro** [comment]
Tiếng Việt: https://odinland.vn/danh-muc/tin-tuc/
Tiếng Anh: https://odinland.vn/category/news/?lang=en

Anh có thấy phần nào không hiển thị đâu @tanlucbui 

Bình thường thì không cần, nhưng mình dùng đa ngôn ngữ thì mọi thứ phải giữ nguyên.
