### ISSUE TITLE
Category: Translation

### ISSUE THREAD

**Issue by khoipro** [caresvn/odinland.vn#70]
![a7d1dbaaecd60b8852c7](https://user-images.githubusercontent.com/10395311/63315791-b4c57300-c336-11e9-93b2-46d9a11c0626.jpg)

Cần chuyển tiếng Việt cho mục "Posted on".

Link: https://odinland.vn/danh-muc/tin-tuc/tin-tuc-dinh-cu/

**Comment by Minh-Odinland** [comment]
Thêm nữa, để định dạng tháng, chứ ko có định dạng ngày

**Comment by khoipro** [comment]
Đã hoàn thành: https://odinland.vn/danh-muc/tin-tuc/su-kien-hoi-thao/
