### ISSUE TITLE
City Map

### ISSUE THREAD

**Issue by Minh-Odinland** [caresvn/odinland.vn#71]
(+)   Trang chủ: Thêm section City Maps, liệt kê các thành phố (propety location   category)     Lưu ý trong design có yêu cầu bổ sung thêm nút CTA (CTA Text + CTA URL) để   chọn page link về page Comparison.
--

**Comment by khoipro** [comment]
Cái này đã có rồi, các bạn chỉ cần thêm là hiện ra thôi.
