### ISSUE TITLE
Module Step

### ISSUE THREAD

**Issue by Minh-Odinland** [caresvn/odinland.vn#72]
(+)   Trang Định cư: Thêm module Steps (các bước thủ tục) ~ 3 layout khác nhau,   responsive
--

**Comment by khoipro** [comment]
@Minh-Odinland các bạn đang chưa có design các steps kiểu khác nên cần thêm thông tin đã.

**Comment by Minh-Odinland** [comment]
em đưa ra vài style đi em, thấy ổn thì chiến

**Comment by khoipro** [comment]
@Minh-Odinland phần style này bên anh cần báo cho bên em làm chứ bên em không có idea + designer đâu.

**Comment by khoipro** [comment]
Các kiểu sẽ bổ sung thêm (anh Minh gửi qua zalo)

![6cf02e4c52beb5e0ecaf](https://user-images.githubusercontent.com/10395311/65109841-aedcb380-da02-11e9-9039-70d363a3cad6.jpg)

![d7270b0376f191afc8e0](https://user-images.githubusercontent.com/10395311/65109893-b69c5800-da02-11e9-86e6-90b83b3e2c7d.jpg)

![06d6c5cea73c4062192d](https://user-images.githubusercontent.com/10395311/65109976-c4ea7400-da02-11e9-9174-fdd51ff2301f.jpg)

**Comment by khoipro** [comment]
**Đã add:**

<img width="936" alt="Screenshot at Sep 19 00-13-56" src="https://user-images.githubusercontent.com/10395311/65170216-6230c100-da72-11e9-92dd-eed1ac545e67.png">

### Demo các kiểu style mới:

**Duplicate Boxes**

<img width="1397" alt="Screenshot at Sep 19 00-13-12" src="https://user-images.githubusercontent.com/10395311/65170178-4c230080-da72-11e9-9aa2-00a8691c5a34.png">

**Box**

<img width="1338" alt="Screenshot at Sep 19 00-14-43" src="https://user-images.githubusercontent.com/10395311/65170263-7ffe2600-da72-11e9-81df-6c799c8180c4.png">
