### ISSUE TITLE
News 

### ISSUE THREAD

**Issue by Minh-Odinland** [caresvn/odinland.vn#73]
(+)   Danh mục Tin tức: Thêm 4 module mới với cách trình bày bài viết kèm ảnh
--

**Comment by khoipro** [comment]
Cái này có điều chỉnh theo design mới nên cần update lại thành Issue #79.

Phần News Category Template (mỗi danh mục, ví dụ Tin tức định cư Síp) đã làm rồi.

`https://odinland.vn/danh-muc/tin-tuc/`
