### ISSUE TITLE
Private Property

### ISSUE THREAD

**Issue by Minh-Odinland** [caresvn/odinland.vn#74]
(~) Bất   động sản riêng lẻ: Điều chỉnh menu phụ trên các trang Bất động sản riêng   lẻ, bật trạng thái active khi click hoặc scroll qua từng khu vực
--

**Comment by khoipro** [comment]
Đã có rồi.

![Screenshot at Aug 21 22-16-03](https://user-images.githubusercontent.com/10395311/63444680-46c99a80-c461-11e9-83f9-6fe890a06b15.png)
