### ISSUE TITLE
Comparison

### ISSUE THREAD

**Issue by Minh-Odinland** [caresvn/odinland.vn#75]
(+)   Trang mới: So sánh các chương trình Định cư.     Triển khai sử dụng ACF Fields từ các page template sau đó chuyển vào page   Comparison.     Option quan trọng: nếu người dùng chọn hơn 2 chương trình thì hiện mục CTA   Form (Contact Form 7) yêu cầu nhập email + điện thoại thì mới cho tiếp tục so   sánh. Ít hơn 2 thì cho so sánh bình thường.
--

**Comment by Minh-Odinland** [comment]
Thiếu phần đặt pass để lấy contact

**Comment by khoipro** [comment]
Đã đẩy code lên https://odinland.vn/so-sanh-cac-chuong-trinh-dinh-cu/

**Comment by Minh-Odinland** [comment]
![image](https://user-images.githubusercontent.com/54342466/63480736-30e9c300-c4bd-11e9-964a-a81b8b64a097.png)
Thêm cả mục Số đt cho anh em nhé

**Comment by Minh-Odinland** [comment]
có 2 câu hỏi liên quan:
1. Nếu nhiều hơn 6 chương trình thì nó sẽ như thế nào?
2. Chương trình Canana có 4 chương trình riêng thì cái mục so sánh anh sẽ đặt vào đâu em?
3. Ở mỗi trang con thì cho mục so sánh vào đâu em?

**Comment by khoipro** [comment]
> Thêm cả mục Số đt cho anh em nhé

Mục này tự thêm được trong danh sách các Form contact.

**Comment by khoipro** [comment]
> 1. Nếu nhiều hơn 6 chương trình thì nó sẽ như thế nào?

Cái này em sẽ điều chỉnh thành Slider (kéo dài ngang) (bản cập nhật tiếp theo).

> 2. Chương trình Canana có 4 chương trình riêng thì cái mục so sánh anh sẽ đặt vào đâu em?

Cái này là mở rộng tính năng, cân nhắc điều chỉnh ở thời gian khác (trong 1 bản update khác).

> 3. Ở mỗi trang con thì cho mục so sánh vào đâu em?

Có mục tương đương có thể gắn link vào page So sánh.

![Screenshot at Aug 22 09-29-46](https://user-images.githubusercontent.com/10395311/63481377-70191380-c4bf-11e9-934d-b6efa1216ec9.png)

**Comment by Minh-Odinland** [comment]
> > 1. Nếu nhiều hơn 6 chương trình thì nó sẽ như thế nào?
> 
> Cái này em sẽ điều chỉnh thành Slider (kéo dài ngang) (bản cập nhật tiếp theo).
> Sao làm luôn mà cái j cũng tính bản mở rộng hay nâng cấp vậy em?

> > 1. Chương trình Canana có 4 chương trình riêng thì cái mục so sánh anh sẽ đặt vào đâu em?
> 
> Cái này là mở rộng tính năng, cân nhắc điều chỉnh ở thời gian khác (trong 1 bản update khác).
> Làm thì làm luôn chứ em?
> > 1. Ở mỗi trang con thì cho mục so sánh vào đâu em?
> 
> Có mục tương đương có thể gắn link vào page So sánh.
> 
> Module: CTA Block - https://github.com/caresvn/odinland.vn/wiki/Flexible-Template#5-cta-block
> 
> ![Screenshot at Aug 22 09-29-46](https://user-images.githubusercontent.com/10395311/63481377-70191380-c4bf-11e9-934d-b6efa1216ec9.png)

**Comment by khoipro** [comment]
Thêm vào trang con sử dụng module CTA Block:

### Hiển thị

<img width="493" alt="Screenshot at Aug 26 10-12-26" src="https://user-images.githubusercontent.com/10395311/63662812-0fa11380-c7ea-11e9-9f04-fd07e541af5c.png">

### Cấu hình

<img width="461" alt="Screenshot at Aug 26 10-13-23" src="https://user-images.githubusercontent.com/10395311/63662837-2e9fa580-c7ea-11e9-9f76-5efa695ed332.png">

**Comment by khoipro** [comment]
> Sao làm luôn mà cái j cũng tính bản mở rộng hay nâng cấp vậy em? 

@Minh-Odinland 

Bởi vì scope (mục tiêu và thống nhất ban đầu) là dựng lại một tính năng mà website có, và website đó làm kiểu quá đơn giản còn mình là đã tương đối hoàn thiện hơn rồi (có bật popup CTA là khác họ nhiều).

Thêm nữa, bên website để làm đối chiếu cũng không có chức năng kéo dài dạng slider. Nên cái này không được tính là bắt buộc làm ở trong bản cập nhật này.

Tất nhiên việc cần làm web tốt nhất là đúng, nhưng căn cứ theo budget và thời gian nữa anh ạ. Em không cân đối thêm vào được nữa (vì phải điều chỉnh lại báo giá, trong khi báo giá và cập nhật gần nhất là chốt rồi).

**Comment by khoipro** [comment]
@Minh-Odinland em đẩy bản fix lên để lựa chọn hơn 4 item thì sẽ kéo ngang được.

<img width="1380" alt="Screenshot at Sep 04 21-06-16" src="https://user-images.githubusercontent.com/10395311/64262180-e570f380-cf57-11e9-9039-1c494c1abfe0.png">
