### ISSUE TITLE
Module > Page Grid With Tabs > Add Boxes Styles

### ISSUE THREAD

**Issue by Minh-Odinland** [caresvn/odinland.vn#77]
![image](https://user-images.githubusercontent.com/54342466/63399429-b35d7e80-c3fa-11e9-8f96-4161206e6ef8.png)

**Comment by khoipro** [comment]
Update new style @Minh-Odinland 

![Screenshot at Aug 21 22-09-32](https://user-images.githubusercontent.com/10395311/63444218-61e7da80-c460-11e9-9975-34b378dfc6e4.png)

**Comment by khoipro** [comment]
Đã cập nhật xong.
