### ISSUE TITLE
CTA chưa hoạt động

### ISSUE THREAD

**Issue by Minh-Odinland** [caresvn/odinland.vn#78]
![image](https://user-images.githubusercontent.com/54342466/63404073-00961c00-c40c-11e9-8be4-569ad55359b8.png)

**Comment by khoipro** [comment]
Thiếu phần cấu hình popup thì click vào mới hiện ra @Minh-Odinland 

https://github.com/caresvn/odinland.vn/wiki/Flexible-Template#1-popup

**Comment by Minh-Odinland** [comment]
Em thêm cấu hình chưa em?
