### ISSUE TITLE
Program > Setup a Popup

### ISSUE THREAD

**Issue by Minh-Odinland** [caresvn/odinland.vn#81]
Form chưa hoạt động 
![image](https://user-images.githubusercontent.com/54342466/63504536-f7847800-c4fb-11e9-98d1-0229cde057fe.png)

**Comment by khoipro** [comment]
Do chưa nhập cấu hình shortcode contact form.

<img width="468" alt="Screenshot at Aug 26 10-03-06" src="https://user-images.githubusercontent.com/10395311/63662488-c9978000-c7e8-11e9-9edc-9ae9a1f97f38.png">

Vào https://odinland.vn/wp-admin/admin.php?page=wpcf7 tìm cột Shortcode để copy.

**Comment by Minh-Odinland** [comment]
Em làm hộ anh nhé, bên anh các bạn ko biết đâu

**Comment by khoipro** [comment]
Phần này em không làm hộ vì đã có hướng dẫn rồi. Content bên anh phải tự làm nhé anh @Minh-Odinland
