### ISSUE TITLE
Space

### ISSUE THREAD

**Issue by Minh-Odinland** [caresvn/odinland.vn#82]
![image](https://user-images.githubusercontent.com/54342466/63558600-aca84600-c577-11e9-9015-f0a5b199aff7.png)
 Khoảng cách 2 cột ở menu này xa quá

**Comment by khoipro** [comment]
Cái này làm theo yêu cầu của marketing (để nhập được nhiều mục hơn). Không thay đổi thêm nữa trừ khi có confirm lần nữa từ bên marketing anh @Minh-Odinland nhé. (vì thay đổi theo tự phát).
