### ISSUE TITLE
Single Post > Breadcrumbs > Category Link

### ISSUE THREAD

**Issue by Minh-Odinland** [caresvn/odinland.vn#84]
![image](https://user-images.githubusercontent.com/54342466/63904810-7289e900-ca3c-11e9-8cfd-fcb1ddfd99a6.png)

Không biết ra ngoài ở mục tin tức mẹ ở chỗ nào cả

**Comment by khoipro** [comment]
<img width="638" alt="Screenshot at Aug 29 16-44-54" src="https://user-images.githubusercontent.com/10395311/63929843-57d76480-ca7c-11e9-94b2-99cdb667c531.png">

Hiên tại các bạn đang cho nhiều category cho một bài viết. Phần hiển thị ở ngay dưới tiêu đề bài viết là có thể click để vào danh mục cha của bài viết.

Ngoài ra phần đường dẫn phía trên chỉ cho hiển thị 1 link thôi.

**Comment by khoipro** [comment]
Cái này em không fix mà bên anh phải bỏ phần đánh dấu các category cha và chỉ set 1 category duy nhất cho bài viết (Post) thôi nhé anh @Minh-Odinland.

<img width="301" alt="Screenshot at Sep 04 20-11-42" src="https://user-images.githubusercontent.com/10395311/64257844-501e3100-cf50-11e9-9c5b-738f4a015fc1.png">
