### ISSUE TITLE
Không có link trang chủ tin tức

### ISSUE THREAD

**Issue by Minh-Odinland** [caresvn/odinland.vn#85]

**Comment by khoipro** [comment]
Đã add vào trong post và category.

Post:

<img width="770" alt="Screenshot at Sep 04 20-51-37" src="https://user-images.githubusercontent.com/10395311/64260877-d38e5100-cf55-11e9-8a64-5afc6886a244.png">

Category:

<img width="614" alt="Screenshot at Sep 04 20-52-06" src="https://user-images.githubusercontent.com/10395311/64260898-df7a1300-cf55-11e9-861e-160e9e055961.png">

Settings để chọn trang:

<img width="1279" alt="Screenshot at Sep 04 20-52-32" src="https://user-images.githubusercontent.com/10395311/64260972-f587d380-cf55-11e9-8637-c8e11953b97e.png">
