### ISSUE TITLE
Bố cục lại ảnh ở tin tức cho dễ nhìn, bắt mắt

### ISSUE THREAD

**Issue by Minh-Odinland** [caresvn/odinland.vn#86]
![image](https://user-images.githubusercontent.com/54342466/63904982-f512a880-ca3c-11e9-9c0a-3df7ecdfbcc8.png)

**Comment by khoipro** [comment]
Đã đẩy lại cho cân đối hơn.

<img width="1278" alt="Screenshot at Sep 04 20-23-43" src="https://user-images.githubusercontent.com/10395311/64258705-ebfc6c80-cf51-11e9-9a7f-c998d471027c.png">
