### ISSUE TITLE
Vẫn còn tiếng anh, chỗ more đó nên để link ấn vào là đọc thêm

### ISSUE THREAD

**Issue by Minh-Odinland** [caresvn/odinland.vn#89]
![image](https://user-images.githubusercontent.com/54342466/64486657-e22c7f00-d259-11e9-89b8-e8ac3bff68c9.png)

**Comment by khoipro** [comment]
Đã bỏ luôn phần text này.

![Screenshot at Sep 18 16-38-43](https://user-images.githubusercontent.com/10395311/65137023-d186c080-da32-11e9-94b6-0695ca8e25ec.png)
