### ISSUE TITLE
Sửa lại theme contact

### ISSUE THREAD

**Issue by Minh-Odinland** [caresvn/odinland.vn#90]
![image](https://user-images.githubusercontent.com/54342466/64962192-34f0e100-d8c1-11e9-806c-b0025d463c22.png)
Theme này xấu quá, ko hấp dẫn gì cả

**Comment by khoipro** [comment]
Anh cho em demo cái nào đẹp nhé @Minh-Odinland vì cái này bên anh không cung cấp design.

**Comment by Minh-Odinland** [comment]
Cái này thì sao em?

https://offers.hubspot.com/contact-sales-now?utm_expid=.IRJD7hO9RsS_quGUsRlXNA.1&utm_referrer=https%3A%2F%2Foffers.hubspot.com%2Fcontact-sales-now%3F_ga%3D2.75937109.1750141523.1568687600-392563588.1568687600

**Comment by Minh-Odinland** [comment]
![image](https://user-images.githubusercontent.com/54342466/65128141-16a2f680-da23-11e9-8f5a-3cf546aaaa46.png)

**Comment by Minh-Odinland** [comment]
hai cái đó khá nổi bật về thiết kế, màu sắc, điểm nhấn....

Em làm theo cái đó nhé

**Comment by khoipro** [comment]
Em sẽ làm theo style này: https://offers.hubspot.com/contact-sales-now

Cái phía sau thì không nên vì bên anh là bất động sản, làm kiểu ấy không đúng phong cách, chưa kể trên mobile sẽ không hiển thị đẹp nữa.

**Comment by khoipro** [comment]
Em đính kèm ảnh để confirm.

![screenshot-offers hubspot com-2019 09 19-08_53_01](https://user-images.githubusercontent.com/10395311/65207128-f292f400-daba-11e9-8c6d-ccbb097e6040.png)

**Comment by Minh-Odinland** [comment]
chốt phươn án
