### ISSUE TITLE
Website Speed

### ISSUE THREAD

**Issue by Minh-Odinland** [caresvn/odinland.vn#92]
![image](https://user-images.githubusercontent.com/54342466/64966162-78028280-d8c8-11e9-8bf2-99424a0a0067.png)

**Comment by khoipro** [comment]
https://gtmetrix.com/reports/odinland.vn/qioVoVSA

Website của anh @Minh-Odinland nặng vì tỷ lệ các script cho Google (bao gồm Google Tag Manager, Google Analytics), script quảng cáo (admicro), script chat Facebook ngốn tài nguyên anh nhé.

Để tăng thì cần remove, chứ hiện tại code trên web đã tối ưu hết nấc rồi anh ạ.

Anh có thể vào link báo cáo trên, kiểm tra những phần màu đỏ sẽ thấy toàn là các liên kết đến từ ngoài website, không phải từ trong odinland.vn

**Comment by khoipro** [comment]
<img width="783" alt="Screenshot at Sep 19 01-19-52" src="https://user-images.githubusercontent.com/10395311/65174688-98bf0980-da7b-11e9-8ed7-9b9779fcd62f.png">

<img width="768" alt="Screenshot at Sep 19 01-20-22" src="https://user-images.githubusercontent.com/10395311/65174733-abd1d980-da7b-11e9-8e08-427b696f87bd.png">

<img width="772" alt="Screenshot at Sep 19 01-21-05" src="https://user-images.githubusercontent.com/10395311/65174796-c4da8a80-da7b-11e9-840f-f899276e00ab.png">
