### ISSUE TITLE
SEO Site Audit

### ISSUE THREAD

**Issue by Minh-Odinland** [caresvn/odinland.vn#93]
![image](https://user-images.githubusercontent.com/54342466/64966251-a41e0380-d8c8-11e9-9228-6eafd8b2f546.png)

**Comment by khoipro** [comment]
Sau khi em chạy qua 1 phần fix thì kết quả như sau:

### Error: 53

Trong đó:

**Duplicate Titles: 26**

Các bài viết có trùng tiêu đề (thường là song ngữ, copy qua nhưng không thêm vào, ví dụ "Dự án..." thay vì ghi thẳng tên).

> Cái này bên anh tự fix. Nó là những trang nào thì bên anh liên hệ với bên Marketing để có thông tin, em chỉ report phần thống kê thôi.

Em đính kèm ảnh.

<img width="1015" alt="Screenshot at Sep 19 01-48-25" src="https://user-images.githubusercontent.com/10395311/65177065-30bef200-da80-11e9-9d41-cc6fa12bd5d9.png">

> Resources with 4xx status code

Đây là các bài viết mà bên anh có bản tiếng Anh hoặc tiếng Việt nhưng không có nội dung tương ứng, hoặc có nhưng không set để hai bài kết nối với nhau.

Nó không chỉ là bài viết mà còn cả [danh mục tin tức](https://odinland.vn/wp-admin/edit-tags.php?taxonomy=category), [Locations](https://odinland.vn/wp-admin/edit-tags.php?taxonomy=property_location&post_type=property) và [Types](https://odinland.vn/wp-admin/edit-tags.php?taxonomy=property_type&post_type=property)

**Cách fix:** Sửa category, bài viết, location, type thêm nội dung tương ứng, ví dụ Category "Australia News" thì tương ứng là "Định cư Úc". Hiện tại có cả hai nhưng không chọn để hệ thống hiểu là nó là cùng một nội dung nhưng khác ngôn ngữ.

<img width="656" alt="Screenshot at Sep 19 01-51-30" src="https://user-images.githubusercontent.com/10395311/65177339-b3e04800-da80-11e9-97e6-9f95fd776c01.png">

**Comment by khoipro** [comment]
Đối với phần "Info" (không bắt buộc fix), có các mục sau cần lưu ý:

**- Empty Alt text**

Khi upload ảnh lên website thì cần bổ sung mục "Alternative Text" để SEO cho ảnh.

<img width="408" alt="Screenshot at Sep 19 01-58-33" src="https://user-images.githubusercontent.com/10395311/65177522-07529600-da81-11e9-9f98-46bcfd5aaa6e.png">

**Comment by khoipro** [comment]
## Warning: 579

Có các mục sau cần lưu ý:

**- Too big pages:** (1)

Bài chứa nhiều ảnh nặng nên vượt quá 3MB: https://odinland.vn/homeowners-does-not-recognize-the-4th-level-building-into-hotel-after-renovation/?lang=en

**- Too long titles** (14)

Bài có tiêu đề dài quá.

**- Empty meta description**

Bài không có mô tả cho SEO.

Để sửa, vào các bài viết và click vào khu vực như trong ảnh để nhập nội dung bổ sung "Meta Description"

<img width="876" alt="Screenshot at Sep 19 02-03-07" src="https://user-images.githubusercontent.com/10395311/65177835-b42d1300-da81-11e9-94f7-c52d67d7e690.png">

<img width="682" alt="Screenshot at Sep 19 02-03-33" src="https://user-images.githubusercontent.com/10395311/65177855-bee7a800-da81-11e9-965e-4b1a39d09d41.png">

**Comment by khoipro** [comment]
Như vậy em đã thống kê các hạng mục bên anh tự triển khai phần SEO chứ không phải bên em làm rồi nhé. Phần nào về code (như bên Error, từ 1024 lỗi về 53) là do em chạy code fix rồi @Minh-Odinland
