### ISSUE TITLE
Sửa string

### ISSUE THREAD

**Issue by Admin-Odinland** [caresvn/odinland.vn#96]
Dịch string thì okay rồi. Nhung để sửa bản tiếng anh như hình thì sửa ở đâu vì dòng "More from OdinLand" thành" More from Odin Land" ạ
![Capture](https://user-images.githubusercontent.com/56016493/65952806-df920380-e46c-11e9-94db-f7de03c11fa5.PNG)

**Comment by khoipro** [comment]
Đã fix rồi nhé, cần sửa bản dịch tiếng Việt lại nữa là ok.

Demo: https://odinland.vn/lua-dao-nhap-cu-vao-canada-se-som-bi-xoa-so/
